import{a as y,S as L,i}from"./assets/vendor-BzwzYqr9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const b="45519676-8baf865f5b6a7e52cd4b281c8";async function p(r,s){const e=new URLSearchParams({key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}),{data:n}=await y(`https://pixabay.com/api/?${e}`);return n}const w=document.querySelector("#gallery");function m(r){const s=r.map(e=>`
     <li class="image-card">
            <a href="${e.largeImageURL}"><img src="${e.webformatURL}" class="card-img" alt="${e.tags}" /></a>
        <ul class="description">
        <li><p>likes:</p><p>${e.likes}</p></li>
        <li><p>views:</p><p>${e.views}</p></li>
        <li><p>comments:</p><p>${e.comments}</p></li>
        <li><p>downloads:</p><p>${e.downloads}</p></li>
        </ul>
        </li>
    `).join("");w.insertAdjacentHTML("beforeend",s),v.refresh()}const v=new L(".image-card a",{captionsData:"alt",captionDelay:250}),h=document.querySelector(".serch-form"),f=document.querySelector("#gallery"),l=document.querySelector(".loader"),d=document.querySelector(".load-more");h.addEventListener("submit",S);d.addEventListener("click",P);let c="",a=1;async function S(r){r.preventDefault();const{serchInput:s}=r.currentTarget.elements;if(c=s.value.trim(),f.innerHTML="",a=1,c==="")return i.error({position:"topRight",message:"Please fill in the fields"});l.classList.remove("hiden");try{const e=await p(c,a);if(e.hits.length===0)return d.classList.add("hiden"),i.warning({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});m(e.hits),g(),h.reset(),e.totalHits>15&&d.classList.remove("hiden")}catch(e){i.error({position:"topRight",message:e.message})}finally{l.classList.add("hiden")}}async function P(){l.classList.remove("hiden"),a+=1;try{const r=await p(c,a);m(r.hits),g(),Math.ceil(r.totalHits/15)===a&&(d.classList.add("hiden"),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch(r){i.error({position:"topRight",message:r.message})}finally{l.classList.add("hiden")}}function g(){const{height:r}=f.lastElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
